image: docker:latest

variables:
  GOOGLE_TAG: eu.gcr.io/papers-kubernetes/acurast-typescript-sdk:$CI_COMMIT_SHA
  GOOGLE_TAG_LATEST: eu.gcr.io/papers-kubernetes/acurast-typescript-sdk:latest

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - docker build -t $GOOGLE_TAG .
  tags:
    - docker

test:
  stage: test
  before_script:
    - docker rm -f unit-$CI_COMMIT_SHA || true
  script:
    - docker run --name unit-$CI_COMMIT_SHA $GOOGLE_TAG /bin/bash -c "yarn test:ci"
  after_script:
    - docker rm -f unit-$CI_COMMIT_SHA || true
  tags:
    - docker

publish_beta:
  stage: publish
  when: manual
  script:
    - docker run --env NPM_AUTH_TOKEN --name unit-$CI_COMMIT_SHA $GOOGLE_TAG ./npm-ci-publish-beta-only.sh
  tags:
    - docker

publish:
  stage: publish
  only:
    - main
  when: manual
  script:
    - docker run --env NPM_AUTH_TOKEN --name unit-$CI_COMMIT_SHA $GOOGLE_TAG ./npm-ci-publish.sh
  tags:
    - docker